### ISSUE TITLE
Idea: add support for phpstan OR split this repo between Zf1 stubs and the psalm plugin

### ISSUE THREAD

**Issue by fredericgboutin-yapla** [matthewbdaly/psalm-plugin-zendframework1#2]
I'm using [phpstan](https://phpstan.org/user-guide/stub-files). I came to realize that I need those juicy stubs you created.

I can always install your composer module and include the stub file directly like so,

```neon
parameters:
    stubFiles:
        - vendor/matthewbdaly/psalm-plugin-zendframework1/src/Stubs/zendframework1.phpstub
```

But this is a workaround and I end-up with a dependency on psalm.

I suppose the solution could be to make your stubs more generally available - i.e. you create a `matthewbdaly/zendframework1-stubs` project and then you add a dependency on it? I dunno.

**Comment by matthewbdaly** [comment]
I'm open to this idea, but I'm not sure it would be worth the bother to maintain two separate packages for it.

I created this package due to one legacy project I maintain at work and it was initially generated automatically and then has just been amended by hand to fix a few incorrect type annotations and access levels.

Obviously Zend 1 isn't a moving target so keeping it up to date isn't an issue, and I last applied a change about a year ago so activity is never going to be high - any additional changes I might make in future would likely only be quite minor tweak. As such I don't think any hypothetical stubs package would be likely to see any additional activity, so it you wanted to lift them out and reuse them in a PHPStan package that wouldn't be likely to need any updates, and if you want to take that approach I'm happy for you to do so.

Alternatively I don't think Psalm actually needs to be a dependency. I think it would probably be fine as a dev dependency and I think that would solve your issue?

**Comment by fredericgboutin-yapla** [comment]
> Zend 1 isn't a moving target

More so than you might think. We are using a supported fork version and there are a couple of these out there,

- https://github.com/zf1s/zf1
- https://github.com/Shardj/zf1-future
- https://github.com/diablomedia/zf1

They are adding support for recent versions of PHP so they have to adjust the code a bit.

>  I think that would solve your issue?

Yeah... I spoke a bit too soon. The stubs you created helped me initially but phpstan requires them to be virtually perfect and they are not (I'm not blaming you by any means when saying that). So, I kind of realize that creating stubs is a big B plan in general. 

The framework itself should properly type and phpdoc its source code so we avoid having to define stubs in the first place. 

Sure, you can create an extension with custom rules to help the linter understand things like in the case of Zend Framework 1, maybe all the templating engine stuff to properly lint phtml files, things like that, but otherwise, in the end, defining stubs yourself seem like a perilous task to me.

**Comment by matthewbdaly** [comment]
Yeah, the project I maintain is likely going to have to migrate to one of those forks at some point as otherwise we're stuck on PHP 7.1 and the OS is in need of updating. So I was somewhat aware of them, just haven't actually used them yet myself.

A big part of why I created this package in the first place is speed. It was taking over ten minutes to run Psalm before whereas once I created this package and introduced it, it took about a tenth of that. It doesn't really surprise me to hear it's not terribly accurate - I auto-generated it in the first place and there are things it got wrong, plus the annotations in Zend 1 itself aren't always accurate either - I often have to use additional annotations and asserts to narrow down from abstract classes to more specific ones. Also it's a huge brick of text so it's hard to track down any inaccuracies.

Honestly, if you're using one of the forks I think you would likely be better off creating a dedicated package with that fork in mind to accommodate any differences that might crop up over time in that fork. If you'd like to use these stub files as a starting point you're welcome to do so.

**Comment by fredericgboutin-yapla** [comment]
> Yeah, the project I maintain is likely going to have to migrate to one of those forks at some point as otherwise we're stuck on PHP 7.1 and the OS is in need of updating. So I was somewhat aware of them, just haven't actually used them yet myself.

Then I would suggest you to start with https://github.com/zf1s/zf1 since it is pretty much a drop-in replacement. We migrated to it a year ago so we could go from 7.1 to 7.4 and now we begin to run 8.2, how incredible is that?

Anyway, thanks for the advices. I suppose we should close the issue then.
